title: Portfolio Manager
description: Art, News, Projects & CV
baseurl: ""
url: "https://pgrassiit.github.io"
author: P. Grassi
email: your-email@example.com
theme: minima

collections:
  art:
    output: true
    permalink: /art/:path/
  news:
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/

defaults:
  - scope:
      path: "_art"
      type: "art"
    values:
      layout: "post"
      category: "art"
  - scope:
      path: "_news"
      type: "news"
    values:
      layout: "post"
      category: "news"
  - scope:
      path: "_projects"
      type: "projects"
    values:
      layout: "post"
      category: "projects"

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - .gitignore
  - .jekyll-cache
  - .sass-cache
  - Gemfile
  - Gemfile.lock
